import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg import sql


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SQLITE_DB = PROJECT_ROOT / "SUPPLEMENTARY ACTIVITIES" / "hardware_inventory.db"
SQLITE_DB = Path(os.environ.get("SQLITE_DB", DEFAULT_SQLITE_DB))
DATABASE_URL = os.environ.get("DATABASE_URL")
TABLE_DEFINITIONS = {
    "users": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT UNIQUE NOT NULL",
        "email TEXT UNIQUE NOT NULL",
        "password_hash TEXT NOT NULL",
        "failed_attempts INTEGER NOT NULL DEFAULT 0",
        "lockout_until DOUBLE PRECISION NOT NULL DEFAULT 0",
        "role TEXT NOT NULL DEFAULT 'USER'",
        "student_name TEXT NOT NULL DEFAULT ''",
        "student_number TEXT NOT NULL DEFAULT ''",
        "section TEXT NOT NULL DEFAULT ''",
    ),
    "hardware": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name TEXT UNIQUE NOT NULL",
        "category TEXT NOT NULL",
        "quantity INTEGER NOT NULL",
        "unit_price DOUBLE PRECISION NOT NULL",
        "status TEXT NOT NULL",
    ),
    "password_reset_requests": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "email TEXT NOT NULL",
        "requested_at DOUBLE PRECISION NOT NULL",
        "status TEXT NOT NULL DEFAULT 'PENDING'",
        "admin_comment TEXT NOT NULL DEFAULT ''",
        "approved_by TEXT NOT NULL DEFAULT ''",
    ),
    "activity_records": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "event_type TEXT NOT NULL",
        "item_id BIGINT",
        "item_name TEXT NOT NULL",
        "username TEXT NOT NULL",
        "quantity INTEGER NOT NULL DEFAULT 0",
        "quantity_delta INTEGER NOT NULL DEFAULT 0",
        "occurred_at DOUBLE PRECISION NOT NULL",
        "details TEXT NOT NULL DEFAULT ''",
    ),
    "borrow_requests": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "item_id BIGINT NOT NULL",
        "quantity INTEGER NOT NULL",
        "purpose TEXT NOT NULL",
        "requested_at DOUBLE PRECISION NOT NULL",
        "status TEXT NOT NULL DEFAULT 'PENDING'",
        "decided_by TEXT NOT NULL DEFAULT ''",
        "decided_at DOUBLE PRECISION NOT NULL DEFAULT 0",
    ),
    "laboratory_reports": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "report_type TEXT NOT NULL",
        "item_id BIGINT",
        "details TEXT NOT NULL",
        "reported_at DOUBLE PRECISION NOT NULL",
        "status TEXT NOT NULL DEFAULT 'OPEN'",
        "reviewed_by TEXT NOT NULL DEFAULT ''",
    ),
    "laboratory_schedules": (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "section TEXT NOT NULL",
        "subject TEXT NOT NULL",
        "instructor TEXT NOT NULL",
        "room TEXT NOT NULL",
        "schedule_date TEXT NOT NULL",
        "start_time TEXT NOT NULL",
        "end_time TEXT NOT NULL",
        "created_by TEXT NOT NULL",
        "created_at DOUBLE PRECISION NOT NULL",
    ),
}


def create_tables(pg_cursor):
    for table_name, columns in TABLE_DEFINITIONS.items():
        definition = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        pg_cursor.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
                sql.Identifier(table_name), definition
            )
        )


def migrate_table(sqlite_cursor, pg_cursor, table_name):
    sqlite_cursor.execute(f'PRAGMA table_info("{table_name}")')
    source_columns = [row[1] for row in sqlite_cursor.fetchall()]
    if not source_columns:
        raise RuntimeError(f"SQLite table '{table_name}' does not exist.")

    pg_cursor.execute(
        sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name))
    )
    if pg_cursor.fetchone()[0] > 0:
        raise RuntimeError(f"Destination table '{table_name}' is not empty.")

    sqlite_cursor.execute(f'SELECT * FROM "{table_name}"')
    rows = sqlite_cursor.fetchall()
    if not rows:
        return 0

    columns = sql.SQL(", ").join(sql.Identifier(column) for column in source_columns)
    placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in source_columns)
    insert_statement = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        sql.Identifier(table_name), columns, placeholders
    )
    pg_cursor.executemany(insert_statement, rows)
    return len(rows)


def reset_identity_sequences(pg_cursor):
    for table_name in TABLE_DEFINITIONS:
        pg_cursor.execute(
            sql.SQL("SELECT MAX({}) FROM {}").format(
                sql.Identifier("id"), sql.Identifier(table_name)
            )
        )
        maximum_id = pg_cursor.fetchone()[0]
        if maximum_id is None:
            continue
        pg_cursor.execute(
            sql.SQL(
                "SELECT setval(pg_get_serial_sequence(%s, %s), "
                "%s, true)"
            ).format(
            ),
            (table_name, "id", maximum_id),
        )


def main():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set.")
    if not SQLITE_DB.exists():
        raise FileNotFoundError(f"SQLite database not found: {SQLITE_DB}")

    sqlite_conn = sqlite3.connect(SQLITE_DB)
    try:
        with psycopg.connect(DATABASE_URL) as pg_conn:
            with pg_conn.cursor() as pg_cursor:
                sqlite_cursor = sqlite_conn.cursor()
                create_tables(pg_cursor)
                counts = {
                    table_name: migrate_table(sqlite_cursor, pg_cursor, table_name)
                    for table_name in TABLE_DEFINITIONS
                }
                reset_identity_sequences(pg_cursor)
            pg_conn.commit()
    finally:
        sqlite_conn.close()

    print("Migration completed successfully.")
    for table_name, count in counts.items():
        print(f"  {table_name}: {count}")


if __name__ == "__main__":
    main()
